title = "Traffic Fines for Bikes"

[changes]
	[changes.20130314]
	author = "sondh"
	reason = "create bike.toml"

[fines]
	[fines.test]
	name                  = "Test Fine"
	description           = "Some description text"
	fine                  = "100000-200000"
	fine_source           = "http://domain.com/source"
	fine_big_city         = ""
	fine_big_city_source  = "http://domain.com/source"
	license_days          = 0
	license_days_source   = "http://domain.com/source"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 0

	[fines.71_2012_ndcp_8_3_c]
	name                  = "Tự ý thay đổi khung, máy, hình dáng, kích thước của xe"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "http://giaothongvn.com/nghi-dinh-71/Diem-c/Khoan-3/Dieu-8/"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1
	
	[fines.43_2010_ndcp_20_1_a]
	name                  = "Không có còi; đèn soi biển số; đèn báo hãm; gương chiếu hậu bên trái người điều khiển hoặc có nhưng không có tác dụng"
	description           = "Phạt tiền từ 80.000 đồng đến 100.000 đồng"
	fine                  = "80000-100000"
	fine_source           = "http://www.chinhphu.vn/portal/page/portal/chinhphu/hethongvanban?class_id=1&mode=detail&document_id=94320"
	fine_big_city         = ""
	fine_big_city_source  = ""
	license_days          = 0
	license_days_source   = ""
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_1]
	name                  = "Tự ý thay đổi nhãn hiệu, màu sơn của xe không đúng với Giấy đăng ký xe"
	description           = "Phạt tiền từ 100.000 đồng đến 200.000 đồng đối với chủ xe mô tô, xe gắn máy và các loại xe tương tự mô tô"
	fine                  = "100000-200000"
	fine_source           = "2012/8/1"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_2_a]
	name                  = "Lắp kính chắn gió, kính cửa của xe không phải là loại kính an toàn"
	description           = "Phạt tiền từ 300.000 đồng đến 500.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "300000-500000"
	fine_source           = "2012/8/2/a"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_2_b]
	name                  = "Tự ý thay đổi màu sơn của xe không đúng với màu sơn ghi trong Giấy đăng ký xe; không thực hiện đúng quy định về biển số, quy định về kẻ chữ trên thành xe và cửa xe; trừ hành vi vi phạm quy định tại Điểm b Khoản 2 Điều 41 của Nghị định này (Cơ sở đào tạo lái xe sử dụng xe tập lái không có “Giấy phép xe tập lái”, biển xe "Tập lái", không ghi tên cơ sở đào tạo, cơ quan quản lý trực tiếp ở mặt ngoài hai bên cánh cửa hoặc hai bên thành xe theo quy định)"
	description           = "Phạt tiền từ 300.000 đồng đến 500.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "300000-500000"
	fine_source           = "2012/8/2/b"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_3_a]
	name                  = "Tự ý đục lại số khung, số máy"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/8/3/a"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_3_b]
	name                  = "Tẩy xóa, sửa chữa hoặc giả mạo hồ sơ đăng ký xe"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/8/3/b"
	license_days          = 9999
	license_days_source   = "2012/8/7/b"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_3_c]
	name                  = "Tự ý thay đổi khung, máy, hình dáng, kích thước của xe"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/8/3/c"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_3_d]
	name                  = "Khai báo không đúng sự thật hoặc sử dụng các giấy tờ, tài liệu giả để được cấp lại biển số, Giấy đăng ký xe"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/8/3/d"
	license_days          = 9999
	license_days_source   = "2012/8/7/b"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_3_dd]
	name                  = "Giao xe hoặc để cho người không đủ điều kiện theo quy định của pháp luật điều khiển xe tham gia giao thông"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/8/3/dd"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_3_e]
	name                  = "Không chuyển quyền sở hữu phương tiện theo quy định"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/8/3/e"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_3_g]
	name                  = "Không mua hoặc nộp phí cho phương tiện khi tham gia giao thông theo quy định"
	description           = "Phạt tiền từ 800.000 đồng đến 1.200.000 đồng đối với chủ xe mô tô, xe gắn máy; các loại xe tương tự mô tô"
	fine                  = "800000-1200000"
	fine_source           = "2012/8/3/g"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_4_a]
	name                  = "Tự ý đục lại số khung, số máy"
	description           = "Phạt tiền từ 2.000.000 đồng đến 4.000.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "2000000-4000000"
	fine_source           = "2012/8/4/a"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_4_b]
	name                  = "Tẩy xóa hoặc sửa chữa Giấy đăng ký xe, hồ sơ đăng ký xe, Giấy chứng nhận hoặc tem kiểm định an toàn kỹ thuật và bảo vệ môi trường hoặc các loại giấy tờ khác về phương tiện"
	description           = "Phạt tiền từ 2.000.000 đồng đến 4.000.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "2000000-4000000"
	fine_source           = "2012/8/4/b"
	license_days          = 9999
	license_days_source   = "2012/8/7/b"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_4_c]
	name                  = "Không chấp hành việc thu hồi Giấy đăng ký xe; biển số xe; Sổ chứng nhận kiểm định an toàn kỹ thuật và bảo vệ môi trường phương tiện giao thông cơ giới đường bộ theo quy định"
	description           = "Phạt tiền từ 2.000.000 đồng đến 4.000.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "2000000-4000000"
	fine_source           = "2012/8/4/c"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_4_d]
	name                  = "Vẽ, dán quảng cáo trên xe không đúng quy định"
	description           = "Phạt tiền từ 2.000.000 đồng đến 4.000.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "2000000-4000000"
	fine_source           = "2012/8/4/d"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_4_dd]
	name                  = "Không làm thủ tục đổi lại Giấy đăng ký xe khi xe đã được cải tạo"
	description           = "Phạt tiền từ 2.000.000 đồng đến 4.000.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "2000000-4000000"
	fine_source           = "2012/8/4/dd"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_4_e]
	name                  = "Giao xe hoặc để cho người không đủ điều kiện theo quy định của pháp luật điều khiển xe tham gia giao thông"
	description           = "Phạt tiền từ 2.000.000 đồng đến 4.000.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "2000000-4000000"
	fine_source           = "2012/8/4/e"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_4_g]
	name                  = "Khai báo không đúng sự thật hoặc sử dụng các giấy tờ, tài liệu giả để được cấp lại biển số, Giấy đăng ký xe"
	description           = "Phạt tiền từ 2.000.000 đồng đến 4.000.000 đồng đối với chủ xe ô tô, máy kéo, xe máy chuyên dùng và các loại xe tương tự ô tô"
	fine                  = "2000000-4000000"
	fine_source           = "2012/8/4/g"
	license_days          = 9999
	license_days_source   = "2012/8/7/b"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_5_a]
	name                  = "Thuê, mượn linh kiện, phụ kiện của xe ô tô khi kiểm định"
	description           = "Phạt tiền từ 4.000.000 đồng đến 6.000.000 đồng"
	fine                  = "4000000-6000000"
	fine_source           = "2012/8/5/a"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.71_2012_ndcp_8_5_b]
	name                  = "Đưa xe cơ giới, xe máy chuyên dùng không có Giấy chứng nhận hoặc tem kiểm định an toàn kỹ thuật và bảo vệ môi trường theo quy định ra tham gia giao thông"
	description           = "Phạt tiền từ 4.000.000 đồng đến 6.000.000 đồng"
	fine                  = "4000000-6000000"
	fine_source           = "2012/8/5/b"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.43_2010_ndcp_12_1_a]
	name                  = "Không đi đúng phần đường quy định"
	description           = "Cảnh cáo hoặc phạt tiền từ 40.000 đồng đến 60.000 đồng"
	fine                  = "40000-60000"
	fine_source           = "2010/12/1/a"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.43_2010_ndcp_12_1_b]
	name                  = "Không chấp hành hiệu lệnh hoặc chỉ dẫn của đèn tín hiệu, biển báo hiệu, vạch kẻ đường"
	description           = "Cảnh cáo hoặc phạt tiền từ 40.000 đồng đến 60.000 đồng"
	fine                  = "40000-60000"
	fine_source           = "2010/12/1/b"
	fine_big_city         = "60000-80000"
	fine_big_city_source  = "2012/13/46/1"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.43_2010_ndcp_12_1_c]
	name                  = "Không chấp hành hiệu lệnh của người điều khiển giao thông, người kiểm soát giao thông"
	description           = "Cảnh cáo hoặc phạt tiền từ 40.000 đồng đến 60.000 đồng"
	fine                  = "40000-60000"
	fine_source           = "2010/12/1/c"
	fine_big_city         = "60000-80000"
	fine_big_city_source  = "2012/13/46/1"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.43_2010_ndcp_12_2_a]
	name                  = "Mang, vác vật cồng kềnh gây cản trở giao thông"
	description           = "Phạt tiền từ 60.000 đồng đến 80.000 đồng"
	fine                  = "60000-80000"
	fine_source           = "2010/12/2/a"
	fine_big_city         = "80000-120000"
	fine_big_city_source  = "2012/13/46/2"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.43_2010_ndcp_12_2_b]
	name                  = "Vượt qua dải phân cách; đi qua đường không đúng nơi quy định hoặc không bảo đảm an toàn"
	description           = "Phạt tiền từ 60.000 đồng đến 80.000 đồng"
	fine                  = "60000-80000"
	fine_source           = "2010/12/2/b"
	fine_big_city         = "80000-120000"
	fine_big_city_source  = "2012/13/46/2"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.43_2010_ndcp_12_2_c]
	name                  = "Đu, bám vào phương tiện giao thông đang chạy"
	description           = "Phạt tiền từ 60.000 đồng đến 80.000 đồng"
	fine                  = "60000-80000"
	fine_source           = "2010/12/2/c"
	fine_big_city         = "80000-120000"
	fine_big_city_source  = "2012/13/46/2"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1

	[fines.43_2010_ndcp_12_3]
	name                  = "Người đi bộ đi vào đường cao tốc"
	description           = "Phạt tiền từ 80.000 đồng đến 120.000 đồng đối với người đi bộ, trừ người phục vụ việc quản lý, bảo trì đường cao tốc"
	fine                  = "80000-120000"
	fine_source           = "2010/12/3"
	updated_ymd           = 20130314
	active_since_ymd      = 20130314
	active_now            = 1
